server:
  port: 8762
  ssl:
    key-store-type: jks
    key-store: classpath:keystore/springstore.jks
    key-store-password: spring
    key-alias: spring
    trust-store: classpath:keystore/spring_truststore.jks
    trust-store-password: spring
spring:
  application:
    name: zuul-proxy
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true
management:
  endpoints:
    web:
      exposure:
        include: info, health, routes
ribbon:
  ReadTimeout: 60000